services:
  db:
    image: postgres:15
    container_name: washer_db
    restart: always
    environment:
      POSTGRES_USER: washer_user
      POSTGRES_PASSWORD: washer_password
      POSTGRES_DB: washer_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
